version: '2'
services:
  webserver:
    build: ./docker/webserver
    image: eunwaytest_web
    ports:
      - "10084:80"
      - "8443:443"
    volumes:
      - /home/george/Documents/hng-docs/simple-docker/www:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "4306:5306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=db_runwaytest